import os
import textwrap
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict

from dotenv import dotenv_values
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas

OUTPUT_DIR = Path("generated_quotes")
OUTPUT_DIR.mkdir(exist_ok=True)


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def safe_text(value: Any) -> str:
    if value is None:
        return ""
    return str(value)


def draw_wrapped(c: canvas.Canvas, text: str, x: float, y: float, width_chars: int = 92, line_height: int = 12):
    """Draw wrapped text and return the new y position."""
    for paragraph in safe_text(text).split("\n"):
        if not paragraph.strip():
            y -= line_height
            continue
        for line in textwrap.wrap(paragraph, width=width_chars):
            c.drawString(x, y, line)
            y -= line_height
    return y


def page_footer(c: canvas.Canvas, record_id: str):
    c.setFont("Helvetica", 8)
    c.setFillColor(colors.grey)
    c.drawString(0.75 * inch, 0.45 * inch, f"Generated by QuotePilot AI using Qwen Cloud | Record: {record_id}")
    c.setFillColor(colors.black)


def ensure_space(c: canvas.Canvas, y: float, record_id: str, needed: float = 1.0 * inch):
    if y < needed:
        page_footer(c, record_id)
        c.showPage()
        c.setFont("Helvetica", 10)
        return 10.2 * inch
    return y


def generate_quote_pdf(record: Dict[str, Any]) -> Dict[str, Any]:
    """Generate a draft quote PDF from a saved workflow record."""
    OUTPUT_DIR.mkdir(exist_ok=True)

    record_id = safe_text(record.get("id") or datetime.now(timezone.utc).strftime("%Y%m%d%H%M%S"))
    extraction = record.get("extraction", {}) or {}
    workflow = record.get("workflow", {}) or {}
    quote = workflow.get("quote", {}) or {}
    policy = workflow.get("policy", {}) or {}
    email_draft = workflow.get("email_draft", {}) or {}

    file_path = OUTPUT_DIR / f"quotepilot_quote_{record_id}.pdf"

    c = canvas.Canvas(str(file_path), pagesize=letter)
    width, height = letter
    y = height - 0.75 * inch

    # Header
    c.setFillColor(colors.HexColor("#1F2A44"))
    c.rect(0, height - 1.25 * inch, width, 1.25 * inch, fill=True, stroke=False)
    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 22)
    c.drawString(0.75 * inch, height - 0.75 * inch, "QuotePilot AI — Draft Quote")
    c.setFont("Helvetica", 10)
    c.drawString(0.75 * inch, height - 1.02 * inch, "Qwen-powered Autopilot Agent with human approval guard")
    c.setFillColor(colors.black)

    y = height - 1.65 * inch
    c.setFont("Helvetica-Bold", 12)
    c.drawString(0.75 * inch, y, "Customer / Inquiry Summary")
    y -= 0.25 * inch

    c.setFont("Helvetica", 10)
    summary_rows = [
        ("Record ID", record_id),
        ("Created", safe_text(record.get("created_at") or utc_now())),
        ("Customer", safe_text(extraction.get("customer_name") or "Unknown")),
        ("Company", safe_text(extraction.get("company") or "Unknown")),
        ("Email", safe_text(extraction.get("email") or "Not provided")),
        ("Delivery location", safe_text(extraction.get("delivery_location") or "Not provided")),
        ("Deadline", safe_text(extraction.get("deadline") or "Not provided")),
        ("Workflow state", safe_text(workflow.get("workflow_state") or "Unknown")),
        ("Approval required", "YES" if workflow.get("approval_required") else "NO"),
    ]

    for label, value in summary_rows:
        y = ensure_space(c, y, record_id)
        c.setFont("Helvetica-Bold", 9)
        c.drawString(0.75 * inch, y, f"{label}:")
        c.setFont("Helvetica", 9)
        c.drawString(2.25 * inch, y, value[:95])
        y -= 0.18 * inch

    y -= 0.15 * inch
    y = ensure_space(c, y, record_id)
    c.setFont("Helvetica-Bold", 12)
    c.drawString(0.75 * inch, y, "Quote Line Items")
    y -= 0.28 * inch

    line_items = quote.get("line_items", []) or []
    if line_items:
        c.setFont("Helvetica-Bold", 9)
        c.drawString(0.75 * inch, y, "SKU")
        c.drawString(2.35 * inch, y, "Name")
        c.drawString(4.75 * inch, y, "Qty")
        c.drawString(5.35 * inch, y, "Unit")
        c.drawString(6.25 * inch, y, "Line Total")
        y -= 0.18 * inch
        c.line(0.75 * inch, y + 0.08 * inch, 7.35 * inch, y + 0.08 * inch)
        c.setFont("Helvetica", 8.5)
        for item in line_items:
            y = ensure_space(c, y, record_id)
            c.drawString(0.75 * inch, y, safe_text(item.get("sku"))[:20])
            c.drawString(2.35 * inch, y, safe_text(item.get("name"))[:32])
            c.drawRightString(5.0 * inch, y, safe_text(item.get("quantity")))
            c.drawRightString(5.95 * inch, y, f"${float(item.get('unit_price', 0)):,.2f}")
            c.drawRightString(7.35 * inch, y, f"${float(item.get('line_total', 0)):,.2f}")
            y -= 0.2 * inch
    else:
        c.setFont("Helvetica", 9)
        c.drawString(0.75 * inch, y, "No quote line items were created.")
        y -= 0.25 * inch

    y -= 0.1 * inch
    y = ensure_space(c, y, record_id)
    c.setFont("Helvetica-Bold", 12)
    c.drawString(0.75 * inch, y, "Totals")
    y -= 0.25 * inch

    totals = [
        ("Subtotal", quote.get("subtotal", 0)),
        ("Discount", quote.get("discount_amount", 0)),
        ("Shipping estimate", quote.get("shipping_estimate", 0)),
        ("Tax", quote.get("tax_amount", 0)),
        ("Total", quote.get("total", 0)),
    ]

    for label, amount in totals:
        y = ensure_space(c, y, record_id)
        c.setFont("Helvetica-Bold" if label == "Total" else "Helvetica", 10)
        c.drawString(4.75 * inch, y, f"{label}:")
        c.drawRightString(7.35 * inch, y, f"${float(amount or 0):,.2f}")
        y -= 0.2 * inch

    y -= 0.15 * inch
    y = ensure_space(c, y, record_id)
    c.setFont("Helvetica-Bold", 12)
    c.drawString(0.75 * inch, y, "Human Approval / Policy Guard")
    y -= 0.25 * inch
    c.setFont("Helvetica", 9)

    reasons = policy.get("approval_reasons", []) or []
    if reasons:
        for reason in reasons:
            y = ensure_space(c, y, record_id)
            y = draw_wrapped(c, "- " + safe_text(reason), 0.9 * inch, y, width_chars=95, line_height=11)
    else:
        c.drawString(0.9 * inch, y, "No approval reasons listed.")
        y -= 0.2 * inch

    y -= 0.12 * inch
    y = ensure_space(c, y, record_id, needed=1.5 * inch)
    c.setFont("Helvetica-Bold", 12)
    c.drawString(0.75 * inch, y, "Prepared Customer Email Draft")
    y -= 0.25 * inch
    c.setFont("Helvetica", 9)
    y = draw_wrapped(c, "Subject: " + safe_text(email_draft.get("subject")), 0.75 * inch, y, width_chars=95, line_height=11)
    y -= 0.05 * inch
    y = draw_wrapped(c, safe_text(email_draft.get("body")), 0.75 * inch, y, width_chars=95, line_height=11)

    y = ensure_space(c, y, record_id)
    c.setFont("Helvetica-Bold", 9)
    c.setFillColor(colors.red)
    c.drawString(0.75 * inch, y, "Status: DRAFT ONLY — not sent without human approval.")
    c.setFillColor(colors.black)

    page_footer(c, record_id)
    c.save()

    return {
        "pdf_generated": True,
        "file_path": str(file_path),
        "file_name": file_path.name,
        "generated_at": utc_now(),
    }


def get_oss_config() -> Dict[str, str]:
    cfg = dotenv_values(".env")
    return {
        "access_key_id": cfg.get("ALIBABA_CLOUD_ACCESS_KEY_ID", "") or os.getenv("ALIBABA_CLOUD_ACCESS_KEY_ID", ""),
        "access_key_secret": cfg.get("ALIBABA_CLOUD_ACCESS_KEY_SECRET", "") or os.getenv("ALIBABA_CLOUD_ACCESS_KEY_SECRET", ""),
        "endpoint": cfg.get("ALIBABA_OSS_ENDPOINT", "") or os.getenv("ALIBABA_OSS_ENDPOINT", ""),
        "bucket": cfg.get("ALIBABA_OSS_BUCKET", "") or os.getenv("ALIBABA_OSS_BUCKET", ""),
    }


def oss_is_configured() -> bool:
    cfg = get_oss_config()
    return all(cfg.values())


def upload_file_to_oss(file_path: str) -> Dict[str, Any]:
    cfg = get_oss_config()
    missing = [name for name, value in cfg.items() if not value]
    if missing:
        return {
            "oss_uploaded": False,
            "reason": "OSS is not configured.",
            "missing": missing,
        }

    try:
        import oss2

        endpoint = cfg["endpoint"].replace("https://", "").replace("http://", "").strip("/")
        auth = oss2.Auth(cfg["access_key_id"], cfg["access_key_secret"])
        bucket = oss2.Bucket(auth, "https://" + endpoint, cfg["bucket"])

        source_path = Path(file_path)
        object_key = f"quotepilot/quotes/{source_path.name}"
        bucket.put_object_from_file(object_key, str(source_path))

        public_url = f"https://{cfg['bucket']}.{endpoint}/{object_key}"
        return {
            "oss_uploaded": True,
            "bucket": cfg["bucket"],
            "endpoint": endpoint,
            "object_key": object_key,
            "url": public_url,
            "uploaded_at": utc_now(),
        }
    except Exception as e:
        return {
            "oss_uploaded": False,
            "reason": str(e),
        }
